[project]
name = "project"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "angr>=9.2.194",
    "angr-management>=9.2.194",
    "avatar2",
    "setuptools>=80.9.0",
    "typer>=0.24.1",
]

[tool.uv.sources]
avatar2 = { url = "https://github.com/ktpss97094/avatar2/releases/download/v1.4.7+fpv/avatar2-1.4.7+fpv-py3-none-any.whl" }

[tool.uv]
package = true

[tool.ruff]
line-length = 88
target-version = "py312" 
lint.select = ["I", "E", "W", "F"]
lint.ignore = ["E501"]
lint.fixable = ["ALL"]

[tool.ruff.format]
skip-magic-trailing-comma = true
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
verify = "project.main:app"
